### ISSUE TITLE
Undefined index: size when trying to get the listing of a directories with subdirectories

### ISSUE THREAD

**Issue by cramiro** [thephpleague/flysystem-sftp#2]
Let's say your root has

``` bash
-- dir1
   |-- some_dir
   |-- file1.txt
   `-- file2.txt
-- dir2
```

and you connect to that root and ask:

``` php
$contents  = $flysystem->listContents('/dir1');
```

you will get a `Notice` like this:

``` bash
PHP Notice:  Undefined index: size in /your_project/vendor/league/flysystem-sftp/src/SftpAdapter.php on line 205
```

https://github.com/thephpleague/flysystem-sftp/blob/master/src/SftpAdapter.php#L205

Because `$object['type'] == 2` doesn't have `size` index

**Comment by cramiro** [comment]
I can send a PR with a fix.

**Comment by intrepido** [comment]
The problem still happen, because $object some times doesn't have the key `type`. A simple fix would be, change the line `329`:

`$type = ($object['type'] === 1) ? 'file' : 'dir' ;`

for this

`$type = isset($object['type']) && ($object['type'] === 1) ? 'file' : 'dir' ;`

And change the line `310` too:

```
if ($recursive && $object['type'] === NET_SFTP_TYPE_DIRECTORY) {
      $result = array_merge($result, $this->listDirectoryContents($path));
 }
```

for this 

```
if (isset($object['type']) && $recursive && $object['type'] === NET_SFTP_TYPE_DIRECTORY) {
      $result = array_merge($result, $this->listDirectoryContents($path));
 }
```
